# Generated by Django 4.2.28 on 2026-03-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("Comedy", "Comedy"),
                            ("Drama", "Drama"),
                            ("Documentary", "Documentary"),
                            ("Horror", "Horror"),
                            ("Romance", "Romance"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Thriller", "Thriller"),
                        ],
                        default="Drama",
                        max_length=50,
                    ),
                ),
                ("video_file", models.FileField(upload_to="videos/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hls_ready", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-created_at"],
            },
        ),
    ]
